# HTTP Server
server:
  port: ${PORT:3331}   # HTTP port
  
# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:1111/eureka/
      #defaultZone: http://localhost:1111/eureka/
