server:
  port: ${PORT:8888}

logging:
  file: logs/${spring.application.name}.log
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    com.atsistemas: 'DEBUG'   
      
spring:  
  application:
    name: configserver
  cloud:
    config:
      server:
        git:  #Ruta de tu repositorio de configuracion
          uri: https://github.com/lgomezs/spring-respository-config


